version: '3.3'
services:
    nginx:
        restart: on-failure:5
        image: nginx:latest
        container_name: production_nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ${LOG_PATH}/nginx_logs:/var/log/nginx
          - ${SSL_CRT}:/etc/ssl/certs/nginx-selfsigned.crt
          - ${SSL_PVTKEY}:/etc/ssl/private/nginx-selfsigned.key
   
        depends_on:
        #  - claim-service
        #  - ranking-service
           - lucid
        ports:
        #  - ${NGINX_HTTP}:80
         - ${NGINX_HTTPS}:443
          # - 82:82
        networks:
          - app-network

    lucid:
        restart: always
        image: brilliantmd/lucid:${LUCID_VER}
        container_name: lucid
        # ports:
            # - "8080:8080"
        networks: 
            - app-network

        environment:
            APP_PORT: ${LUCID_PORT}
            DB_USERNAME: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_NAME: ${DB_SCHEMA}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${MYSQL_INT_PORT}
            
        command: "node server.js"

        volumes:
            - ${LOG_PATH}/lucid_logs:/home/usr/app/log

    parsing-service:
        image: brilliantmd/parsing_service:${PARSING_VER}
        container_name: parsing_service
        restart: always
        depends_on: 
            - lucid    
        networks:
            - app-network
            
        environment:
            DB_USERNAME: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_NAME: ${DB_SCHEMA}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${MYSQL_INT_PORT}
        
            
            
        command: "python scheduler_script.py"
        volumes:
            - ${LOG_PATH}/parsing_log:/parsing_app/logs
            - ${UPLOADFILE_BASE}:/parsing_app/files/file_upload
            - ${BACKUPFILE_BASE}:/parsing_app/files/file_backup

# Names our volume
volumes:
    logs:
    
networks:
    app-network:
        driver: bridge            